# Generated by Django 5.2.1 on 2026-06-27 12:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('jobs', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_started_at', models.DateTimeField(blank=True, null=True)),
                ('worker_completed_at', models.DateTimeField(blank=True, null=True)),
                ('employer_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employers.employerprofile')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='jobs.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workers.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkin_type', models.CharField(choices=[('start', 'Start'), ('break', 'Break'), ('resume', 'Resume'), ('end', 'End')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('location_text', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('checkin_time', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='assignments.assignment')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='workers.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='assignments.assignment')),
            ],
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_at'], name='assignments_created_300492_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['worker'], name='assignments_worker__226652_idx'),
        ),
    ]
