services:
  db:
    image: postgres:17
    container_name: kazi-buddy-backend-db
    restart: always
    environment:
      POSTGRES_DB: tafakaridb
    env_file:
      - ./tafakari/.env
    ports:
      - "5432:5432"
    volumes:
      - tafakari_db:/var/lib/postgresql/data
    networks:
      - kazi-network-prod

  redis:
    image: redis:alpine
    container_name: kazi-buddy-redis
    restart: unless-stopped
    # no ports needed — only internal container communication
    networks:
      - kazi-network-prod

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kazi-buddy-backend-prod
    command: daphne -b 0.0.0.0 -p 8000 tafakari.asgi:application
    volumes:
      - static_volume:/app/tafakari/staticfiles
      - /var/www/kazibuddy-backend/uploads:/app/tafakari/uploads
      - /var/www/kazibuddy-backend/kazibuddy-backend/tafakari/logs:/app/tafakari/logs
    ports:
      - "8000:8000"
    env_file:
      - ./tafakari/.env
    environment:
      - DEBUG=False
    depends_on:
      - db
      - redis
    networks:
      - kazi-network-prod
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kazi-buddy-celery-prod
    command: celery -A tafakari worker --loglevel=info
    volumes:
      - /var/www/kazibuddy-backend/uploads:/app/tafakari/uploads
      - /var/www/kazibuddy-backend/kazibuddy-backend/tafakari/logs:/app/tafakari/logs
    env_file:
      - ./tafakari/.env
    environment:
      - DEBUG=False
    depends_on:
      - db
      - redis
    networks:
      - kazi-network-prod
    restart: always

volumes:
  static_volume:
  tafakari_db:

networks:
  kazi-network-prod:
    driver: bridge