# Generated by Django 5.2.1 on 2026-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_employer_swap'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='rejection_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='rejection_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
