# Generated by Django 5.2.1 on 2026-10-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_simplify_user_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejection_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejection_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
