# Generated by Django 5.2.1 on 2026-10-03 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('user.approved', 'Approved user'), ('user.deactivated', 'Deactivated user'), ('user.deleted', 'Deleted user'), ('user.deleted_all', 'Deleted all users'), ('user.role_changed', 'Changed user role'), ('admin.invited', 'Invited admin'), ('admin.superadmin_created', 'Created super admin'), ('admin.updated', 'Edited admin'), ('admin.deleted', 'Deleted admin'), ('admin.invite_resent', 'Resent admin invite'), ('job.approved', 'Approved job'), ('job.unapproved', 'Unapproved job'), ('job.created', 'Created job'), ('job.updated', 'Edited job'), ('job.deleted', 'Deleted job'), ('job.status_changed', 'Changed job status'), ('job.featured_toggled', 'Changed featured job'), ('category.created', 'Created category'), ('category.updated', 'Edited category'), ('category.deleted', 'Deleted category'), ('application.status_changed', 'Changed application status'), ('assignment.created', 'Assigned job to worker'), ('assignment.updated', 'Edited assignment'), ('assignment.deleted', 'Removed assignment')], db_index=True, max_length=40)),
                ('target_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('job', 'Job'), ('category', 'Category'), ('application', 'Application'), ('assignment', 'Assignment')], db_index=True, max_length=20)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='auditlogs_a_actor_i_f11990_idx')],
            },
        ),
    ]
