# Generated by Django 5.2.1 on 2026-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user.approved', 'Approved user'), ('user.rejected', 'Rejected user'), ('user.deactivated', 'Deactivated user'), ('user.deleted', 'Deleted user'), ('user.deleted_all', 'Deleted all users'), ('user.role_changed', 'Changed user role'), ('admin.invited', 'Invited admin'), ('admin.superadmin_created', 'Created super admin'), ('admin.updated', 'Edited admin'), ('admin.deleted', 'Deleted admin'), ('admin.invite_resent', 'Resent admin invite'), ('job.approved', 'Approved job'), ('job.unapproved', 'Unapproved job'), ('job.rejected', 'Rejected job'), ('job.created', 'Created job'), ('job.updated', 'Edited job'), ('job.deleted', 'Deleted job'), ('job.status_changed', 'Changed job status'), ('job.featured_toggled', 'Changed featured job'), ('category.created', 'Created category'), ('category.updated', 'Edited category'), ('category.deleted', 'Deleted category'), ('application.status_changed', 'Changed application status'), ('assignment.created', 'Assigned job to worker'), ('assignment.updated', 'Edited assignment'), ('assignment.deleted', 'Removed assignment')], db_index=True, max_length=40),
        ),
    ]
