from .views import (
    JobCategoriesListView,
    JobCategoryDetailView,
    CreateJobCategoryView,
    UpdateJobCategoryView,
    DeleteJobCategoryView,
    JobsInCategoryView,
    JobListView,
    JobDetailView,
    CreateJobView,
    UpdateJobView,
    DeleteJobView,
    JobSkillsView,
    UpdateJobStatusView,
    ToggleFeaturedJobView,
    JobsByEmployerView,
    ListJobsByCategoryView,
    ListJobsByFilterView,
    JobSkillsListView,
    JobSkillDetailView,
    CreateJobSkillView,
    UpdateJobSkillView,
    DeleteJobSkillView,
    JobEmployerView,
    FeaturedJobsView,
    SearchJobsView,
    TotalJobsView,
    TotalJobCategoriesView,
    ListJobsWithApplicationsView,
    ListDraftJobsView,
    ListActiveJobsView,
    ApprovedJobsByEmployerView,
    AssignedJobsByEmployerView
)

from django.urls import path

urlpatterns = [
    path('categories/', JobCategoriesListView.as_view(), name='job-categories-list'),
    path('categories/<uuid:category_id>/', JobCategoryDetailView.as_view(), name='job-category-detail'),
    path('categories/create/', CreateJobCategoryView.as_view(), name='create-job-category'),
    path('categories/update/<uuid:category_id>/', UpdateJobCategoryView.as_view(), name='update-job-category'),
    path('categories/delete/<uuid:category_id>/', DeleteJobCategoryView.as_view(), name='delete-job-category'),
    path('categories/<uuid:category_id>/jobs/', JobsInCategoryView.as_view(), name='jobs-in-category'),
    path('', JobListView.as_view(), name='job-list'),
    path('<uuid:job_id>/', JobDetailView.as_view(), name='job-detail'),
    path('create/', CreateJobView.as_view(), name='create-job'),
    path('update/<uuid:job_id>/', UpdateJobView.as_view(), name='update-job'),
    path('delete/<uuid:job_id>/', DeleteJobView.as_view(), name='delete-job'),
    path('<uuid:job_id>/skills/', JobSkillsView.as_view(), name='job-skills'),
    path('<uuid:job_id>/status/', UpdateJobStatusView.as_view(), name='update-job-status'),
    path('<uuid:job_id>/toggle-featured/', ToggleFeaturedJobView.as_view(), name='toggle-featured-job'),
    path('employers/', JobsByEmployerView.as_view(), name='jobs-by-employer'),
    path('category/<uuid:category_id>/filter/', ListJobsByCategoryView.as_view(), name='list-jobs-by-category'),
    path('jobs/filter/', ListJobsByFilterView.as_view(), name='list-jobs-by-filter'),
    path('skills/', JobSkillsListView.as_view(), name='job-skills-list'),
    path('skills/<uuid:skill_id>/', JobSkillDetailView.as_view(), name='job-skill-detail'),
    path('skills/create/<uuid:job_id>/', CreateJobSkillView.as_view(), name='create-job-skill'),
    path('skills/update/<uuid:skill_id>/', UpdateJobSkillView.as_view(), name='update-job-skill'),
    path('skills/delete/<uuid:skill_id>/', DeleteJobSkillView.as_view(), name='delete-job-skill'),
    path('employer/<uuid:job_id>/', JobEmployerView.as_view(), name='jobs-by-employer-id'),
    path('featured/', FeaturedJobsView.as_view(), name='featured-jobs'),
    path('search/', SearchJobsView.as_view(), name='search-jobs'),
    path('total/', TotalJobsView.as_view(), name='total-jobs'),
    path('categories/total/', TotalJobCategoriesView.as_view(), name='total-job-categories'),
    path('with-applications/', ListJobsWithApplicationsView.as_view(), name='list-jobs-with-applications'),
    path('draft/', ListDraftJobsView.as_view(), name='list-draft-jobs'),
    path('active/', ListActiveJobsView.as_view(), name='list-active-jobs'),
    path('approved/<uuid:employer_id>/', ApprovedJobsByEmployerView.as_view(), name='approved-jobs-by-employer'),
    path('assigned/<uuid:employer_id>/', AssignedJobsByEmployerView.as_view(), name='assigned-jobs-by-employer'),
]